package id.shaderboi.anilist.core.domain.model.anime

data class Anime(
    val aired: Aired,
    val airing: Boolean,
    val background: String?,
    val broadcast: Broadcast?,
    val demographics: List<Demographic>,
    val duration: String,
    val episodes: Int?,
    val explicitGenres: List<ExplicitGenre>,
    val favorites: Int,
    val genres: List<Genre>,
    val images: Images,
    val licensors: List<Licensor>,
    val malId: Int,
    val members: Int,
    val popularity: Int,
    val producers: List<Producer>,
    val rank: Int?,
    val rating: String,
    val score: Float?,
    val scoredBy: Int?,
    val season: String?,
    val source: String,
    val status: String,
    val studios: List<Studio>,
    val synopsis: String?,
    val themes: List<Theme>,
    val title: String,
    val titleEnglish: String?,
    val titleJapanese: String?,
    val titleSynonyms: List<String>,
    val trailer: Trailer?,
    val type: String,
    val url: String,
    val year: Int?
)